export const en = {
  app_title: "Medication Regimen Complexity Calculator",
  disclaimer: "This tool is intended to support clinical decision-making. It does not replace professional clinical judgment.",
  nav: { input: "Input", validation: "Validation", results: "Results", comparison: "Comparison", help: "Help / About", reset: "Reset" },
  buttons: { add: "Add medication", delete: "Delete", save: "Save session", duplicate: "Duplicate", calculate: "Calculate scores", parse: "Parse text", add_parsed: "Send parsed rows to medication table", confirm_review: "I confirm rows were reviewed", apply_corrections: "Apply corrections + recalculate", print: "Print", export_json: "Export JSON", export_csv: "Export CSV", import: "Import" },
  labels: { language: "Language", scoring_mode: "Scoring mode", input_mode: "Input mode", manual_entry: "Manual entry", ai_assist: "AI-assisted text parsing", load_session: "Load previous session…", free_text: "Paste free text", extraction_preview: "Structured extraction preview", parser: "Parser", total_candidates: "Total candidates", reviewed_required: "All AI-parsed medications must be manually validated before scoring.", loading: "Loading mappings...", no_parsed_rows: "No parsed rows yet.", manual_workflow_active: "Manual workflow active. Add rows directly below.", run_to_see_results: "Run validation and calculate to see results.", validated_count: "Validated medications scored", comparison_required_med: "Comparison mode required for medication-level deltas.", comparison_required_section: "Comparison mode required for section-level deltas.", no_warnings: "No mapping warnings detected.", no_validation_issues: "No validation issues detected.", ai_review_blocking: "AI-assisted parsing requires explicit human review confirmation before scoring.", ctrl_multi: "Ctrl/Cmd+click for multiple", evidence: "Evidence", selected_directions: "Selected directions", none: "none", missing: "(missing)", yes: "Yes", no: "No", warning: "Warning", error: "Error", valid: "Valid", notes_review_needed: "Needs manual review", why_score: "Why this score?", section_breakdown: "Section breakdown", row_actions: "Row actions", report_title: "Printable Comparison Report", summary: "Summary", by_medication: "By medication", by_section: "By section", mapping_warnings: "Mapping warnings", low_confidence: "Low confidence", no_mapping_warnings: "No mapping warnings.", help_body: "Local-first clinical support tool. Validate all parsed entries before scoring. Data remains in your browser storage.", score_explanation: "Medication-level contribution", manual_correction: "Manual correction", no_data: "N/A", session_label_prompt: "Session label", session_label_default: "Clinical review" },
  tooltips: { dosage_form: "Dosage form as documented in regimen (tablet, inhaler, drops, etc.).", frequency: "Frequency interpretation follows configured alias mappings.", instructions: "Additional instructions influence section C scoring and warning flags." },
  warnings: { unmapped: "Unmapped", needs_manual_review: "needs manual review", missing_drug_name: "Missing drug name", unknown_dosage_form: "Unknown dosage form", ambiguous_frequency: "Ambiguous frequency", tapering_regimen: "Tapering regimen", alternating_dose: "Alternating dose", possible_duplicate: "Possible duplicate", assumed_not_prn: "Assumed not PRN", one_or_more_missing: "One or more A-MRCI additional direction mappings missing", amrci_form_unmapped: "A-MRCI dosage form not mapped", amrci_frequency_unmapped: "A-MRCI frequency not mapped" },
  results: { mrci_total: "MRCI Total", amrci_total: "A-MRCI Total", abs_diff: "Absolute Difference", section_a: "Section A", section_b: "Section B", section_c: "Section C", drug: "Drug", strength: "Strength", dosage_form: "Dosage form", route: "Route", frequency: "Frequency", prn: "PRN", additional_instructions: "Additional instructions", notes: "Notes", validated: "Validated", type: "Type", field: "Field", message: "Message", rules_applied: "Rules applied", section_diff: "Section diff", total: "Total" },
  parsing: { flags: "Flags", low_confidence_fields: "Low confidence fields", source_text: "Evidence" },
  errors: { drug_required: "Drug name required", dosage_required: "Dosage form required", frequency_required: "Frequency required" },
  modes: { classic: "MRCI only", amrci: "A-MRCI only", compare: "Compare both" }
};
