export const defaultMedication = () => ({
  id: crypto.randomUUID(),
  drugName: "",
  strength: "",
  dosageForm: "",
  route: "",
  dosageFormRoute: "",
  frequency: "",
  prn: false,
  additionalInstructions: "",
  notes: "",
  source: "manual",
  sourceEvidence: "",
  confidence: {},
  extractionFlags: [],
  validated: false,
  manuallyCorrected: false,
  cimaPresentation: "",
  cimaNationalCode: "",
  cimaRegistrationNumber: "",
  cimaActiveIngredients: "",
  cimaDose: "",
  cimaSupplyIssue: false,
  cimaSafetyNotes: []
});

export const defaultSession = () => ({
  id: crypto.randomUUID(),
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  language: "en",
  patientLabel: "",
  regimenLabel: "",
  scoringMode: "compare",
  inputMode: "manual",
  rawInputText: "",
  lastParseResult: null,
  lastValidatedRegimen: null,
  manualCorrectionsLog: [],
  aMrciCorrections: {},
  medications: []
});
